teste1

diff --git a/.github/workflows/helm-ci.yaml b/.github/workflows/helm-ci.yaml
--- a/.github/workflows/helm-ci.yaml
+++ b/.github/workflows/helm-ci.yaml
@@ -93,14 +93,13 @@ jobs:
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
 
-          ls -aR
-          
-          if ! git add .; then
-            echo "Error: Failed to stage the changes for commit."
-            exit 1
-          fi
-          
-          if ! git diff --quiet; then
+          if [[ $(git status --porcelain) ]]; then
+            
+            if ! git add .; then
+              echo "Error: Failed to stage the changes for commit."
+              exit 1
+            fi
+            
             if ! git commit -m "Updated from ref: ${{ github.sha }}"; then
               echo "Error: Failed to commit the changes."
               exit 1
